/**
 * Learned Rules Store
 *
 * Persists rules generated by the reflection engine. Rules are applied
 * during subsequent runs to improve PII detection, strategy selection,
 * and redaction quality.
 *
 * Storage: chrome.storage.local
 * Key: "vless-learned-rules"
 */

import type { LearnedRule, ReflectionResult } from "./reflection.js";

// ─── Storage ────────────────────────────────────────────────────────────────

const STORAGE_KEY = "vless-learned-rules";
const MAX_RULES = 500;

async function getRules(): Promise<LearnedRule[]> {
  const { [STORAGE_KEY]: rules } = await chrome.storage.local.get(STORAGE_KEY);
  return rules ?? [];
}

async function saveRules(rules: LearnedRule[]): Promise<void> {
  if (rules.length > MAX_RULES) {
    // Keep highest-confidence rules.
    rules.sort((a, b) => b.confidence - a.confidence);
    rules.length = MAX_RULES;
  }
  await chrome.storage.local.set({ [STORAGE_KEY]: rules });
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Apply reflection results: store new rules, confirm existing ones.
 */
export async function applyReflectionResults(results: ReflectionResult): Promise<void> {
  const rules = await getRules();

  // Add new rules.
  for (const newRule of results.newRules) {
    // Deduplicate by checking if a rule with the same condition already exists.
    const exists = rules.some(
      (r) =>
        r.category === newRule.category &&
        r.pattern.condition === newRule.pattern.condition &&
        r.pattern.domain === newRule.pattern.domain,
    );
    if (!exists) {
      rules.push(newRule);
    }
  }

  // Confirm existing rules.
  for (const ruleId of results.confirmedRules) {
    const rule = rules.find((r) => r.id === ruleId);
    if (rule) {
      rule.confirmedCount++;
      rule.confidence = Math.min(1.0, rule.confidence + 0.1);
      rule.lastConfirmedAt = Date.now();
    }
  }

  // Contradict rules (reduce confidence).
  for (const ruleId of results.contradictedRules) {
    const rule = rules.find((r) => r.id === ruleId);
    if (rule) {
      rule.confidence = Math.max(0.0, rule.confidence - 0.2);
      // Remove rules that drop below threshold.
      if (rule.confidence < 0.1) {
        const idx = rules.indexOf(rule);
        if (idx >= 0) rules.splice(idx, 1);
      }
    }
  }

  await saveRules(rules);
}

/**
 * Get all learned rules.
 */
export async function getLearnedRules(): Promise<LearnedRule[]> {
  return getRules();
}

/**
 * Get rules that apply to a specific domain and page type.
 */
export async function getApplicableRules(
  domain: string,
  pageType: string,
): Promise<LearnedRule[]> {
  const rules = await getRules();
  return rules.filter((r) => {
    // Rule applies if no domain restriction or domain matches.
    if (r.pattern.domain && r.pattern.domain !== domain) return false;
    // Rule applies if no page type restriction or page type matches.
    if (r.pattern.pageType && r.pattern.pageType !== pageType) return false;
    // Only return rules with sufficient confidence.
    return r.confidence >= 0.3;
  });
}

/**
 * Get rules by category.
 */
export async function getRulesByCategory(
  category: LearnedRule["category"],
): Promise<LearnedRule[]> {
  const rules = await getRules();
  return rules.filter((r) => r.category === category);
}

export interface RuleSummaryItem {
  id: string;
  category: LearnedRule["category"];
  description: string;
  confidence: number;
  confirmedCount: number;
  createdAt: number;
}

/**
 * Get a summary of rules for the dashboard, including the actual rule
 * contents (most recent first) so learning is visible — not just counts.
 */
export async function getRulesSummary(): Promise<{
  total: number;
  byCategory: Record<string, number>;
  highConfidence: number;
  recentlyCreated: number;
  recent: RuleSummaryItem[];
}> {
  const rules = await getRules();
  const oneHourAgo = Date.now() - 60 * 60 * 1000;

  const byCategory: Record<string, number> = {};
  let highConfidence = 0;
  let recentlyCreated = 0;

  for (const rule of rules) {
    byCategory[rule.category] = (byCategory[rule.category] ?? 0) + 1;
    if (rule.confidence >= 0.7) highConfidence++;
    if (rule.createdAt > oneHourAgo) recentlyCreated++;
  }

  const recent = [...rules]
    .sort((a, b) => b.createdAt - a.createdAt)
    .slice(0, 10)
    .map((r) => ({
      id: r.id,
      category: r.category,
      description: r.description,
      confidence: r.confidence,
      confirmedCount: r.confirmedCount,
      createdAt: r.createdAt,
    }));

  return {
    total: rules.length,
    byCategory,
    highConfidence,
    recentlyCreated,
    recent,
  };
}

/**
 * Clear all learned rules.
 */
export async function clearLearnedRules(): Promise<void> {
  await chrome.storage.local.remove(STORAGE_KEY);
}

/**
 * Check if a PII detection should be skipped based on learned rules.
 * Returns true if the detection is a known false positive.
 */
export async function isKnownFalsePositive(
  domain: string,
  pageType: string,
  piiKind: string,
  method: string,
): Promise<boolean> {
  const rules = await getRules();
  return rules.some(
    (r) =>
      r.category === "pii_detection" &&
      r.pattern.condition === `false_positive:${piiKind}:${method}` &&
      (!r.pattern.domain || r.pattern.domain === domain) &&
      (!r.pattern.pageType || r.pattern.pageType === pageType) &&
      r.confidence >= 0.5,
  );
}

/**
 * Get the recommended strategy for a page type.
 */
export async function getRecommendedStrategy(
  pageType: string,
): Promise<"deterministic" | "llm" | null> {
  const rules = await getRules();
  const strategyRules = rules.filter(
    (r) =>
      r.category === "strategy" &&
      r.pattern.pageType === pageType &&
      r.confidence >= 0.5,
  );

  if (strategyRules.length === 0) return null;

  // Return the highest-confidence recommendation.
  strategyRules.sort((a, b) => b.confidence - a.confidence);
  const best = strategyRules[0];
  return best.pattern.action === "use_deterministic" ? "deterministic" : "llm";
}
